---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{{ .Release.Namespace }}"

labels:
  - pairs:
      app.kubernetes.io/managed-by: helm
    includeTemplates: true

resources:
- ../default
- developer-portal

patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kuadrant-system
