apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kuadrant-operator-catalog
spec:
  sourceType: grpc
  image: quay.io/kuadrant/kuadrant-operator-catalog:v1.4.1-rc1
  displayName: Kuadrant Operators
  grpcPodConfig:
    securityContextConfig: restricted
  publisher: grpc
