apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant
spec:
  source: kuadrant-operator-catalog
  sourceNamespace: kuadrant-system
  name: kuadrant-operator
  channel: "alpha"
