---
# Adds namespace to all resources.
namespace: gateway-system
resources:
- namespace.yaml
- gateway-class.yaml
- gateway.yaml
- envoyproxy.yaml
- envoyproxy-cluster-ip.yaml
- gateway-class-cluster-ip.yaml
