apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  name: apiproducts.devportal.kuadrant.io
spec:
  group: devportal.kuadrant.io
  names:
    kind: APIProduct
    listKind: APIProductList
    plural: apiproducts
    singular: apiproduct
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: APIProduct Ready
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      priority: 2
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: APIProduct is the Schema for the apiproducts API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: APIProductSpec defines the desired state of APIProduct.
            properties:
              approvalMode:
                default: manual
                description: whether access requests are auto-approved or require
                  manual review
                enum:
                - automatic
                - manual
                type: string
              contact:
                description: contact information for api owners
                properties:
                  email:
                    description: contact email
                    type: string
                  slack:
                    description: 'slack channel (e.g. #api-support)'
                    type: string
                  team:
                    description: team name
                    type: string
                  url:
                    description: url to team page or support portal
                    type: string
                type: object
              description:
                description: detailed description of the api product
                type: string
              displayName:
                description: human-readable name for the api product
                type: string
              documentation:
                description: api documentation links
                properties:
                  docsURL:
                    description: URL to general documentation
                    type: string
                  gitRepository:
                    description: URL to git repository (shown as view source in backstage)
                    type: string
                  openAPISpecURL:
                    description: URL to openapi specification (json/yaml)
                    type: string
                  swaggerUI:
                    description: URL to swagger ui or similar interactive docs
                    type: string
                  techdocsRef:
                    description: techdocs reference (e.g. url:https://github.com/org/repo
                      or dir:. for local docs)
                    type: string
                type: object
              publishStatus:
                default: Draft
                description: controls whether the api product appears in the backstage
                  catalog (Draft = hidden, Published = visible)
                enum:
                - Draft
                - Published
                type: string
              tags:
                description: tags for categorisation and search
                items:
                  type: string
                type: array
              targetRef:
                description: reference to the httproute that this api product represents
                properties:
                  group:
                    description: Group is the group of the target resource.
                    maxLength: 253
                    pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
                  kind:
                    description: Kind is kind of the target resource.
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    type: string
                  name:
                    description: Name is the name of the target resource.
                    maxLength: 253
                    minLength: 1
                    type: string
                required:
                - group
                - kind
                - name
                type: object
                x-kubernetes-validations:
                - message: Invalid targetRef.group. The only supported value is 'gateway.networking.k8s.io'
                  rule: self.group == 'gateway.networking.k8s.io'
                - message: Invalid targetRef.kind. The only supported value is 'HTTPRoute'
                  rule: self.kind == 'HTTPRoute'
              version:
                description: api version (e.g. v1, v2)
                type: string
            required:
            - approvalMode
            - displayName
            - publishStatus
            - targetRef
            type: object
          status:
            description: APIProductStatus defines the observed state of APIProduct.
            properties:
              conditions:
                description: Represents the observations of a foo's current state.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              discoveredPlans:
                description: list of planpolicies discovered from httproute
                items:
                  properties:
                    limits:
                      description: Limits contains the list of limits that the plan
                        enforces.
                      properties:
                        custom:
                          description: Custom defines any additional limits defined
                            in terms of a RateLimitPolicy Rate.
                          items:
                            description: Rate defines the actual rate limit that will
                              be used when there is a match
                            properties:
                              limit:
                                description: Limit defines the max value allowed for
                                  a given period of time
                                type: integer
                              window:
                                description: Window defines the time period for which
                                  the Limit specified above applies.
                                pattern: ^([0-9]{1,5}(h|m|s|ms)){1,4}$
                                type: string
                            required:
                            - limit
                            - window
                            type: object
                          type: array
                        daily:
                          description: Daily limit of requests for this plan.
                          type: integer
                        monthly:
                          description: Monthly limit of requests for this plan.
                          type: integer
                        weekly:
                          description: Weekly limit of requests for this plan.
                          type: integer
                        yearly:
                          description: Yearly limit of requests for this plan.
                          type: integer
                      type: object
                    tier:
                      description: Tier this plan represents.
                      type: string
                  required:
                  - tier
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration reflects the generation of the most
                  recently observed spec.
                format: int64
                type: integer
              openapi:
                description: OpenAPI specification fetched from the API and its sync
                  status
                properties:
                  lastSyncTime:
                    description: lastSyncTime is the last time the raw content was
                      updated.
                    format: date-time
                    type: string
                  raw:
                    description: raw content
                    type: string
                required:
                - lastSyncTime
                - raw
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
