
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: ratelimitpolicies.apim.kuadrant.io
spec:
  group: apim.kuadrant.io
  names:
    kind: RateLimitPolicy
    listKind: RateLimitPolicyList
    plural: ratelimitpolicies
    singular: ratelimitpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RateLimitPolicy is the Schema for the ratelimitpolicies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RateLimitPolicySpec defines the desired state of RateLimitPolicy
            properties:
              actions:
                description: these actions are used for all of the matching rules
                items:
                  properties:
                    generic_key:
                      properties:
                        descriptor_key:
                          type: string
                        descriptor_value:
                          type: string
                      required:
                      - descriptor_key
                      - descriptor_value
                      type: object
                  required:
                  - generic_key
                  type: object
                type: array
              limits:
                items:
                  description: RateLimitSpec defines the desired state of RateLimit
                  properties:
                    conditions:
                      items:
                        type: string
                      type: array
                    max_value:
                      type: integer
                    namespace:
                      type: string
                    seconds:
                      type: integer
                    variables:
                      items:
                        type: string
                      type: array
                  required:
                  - conditions
                  - max_value
                  - namespace
                  - seconds
                  - variables
                  type: object
                type: array
              networkingRef:
                items:
                  properties:
                    name:
                      type: string
                    type:
                      enum:
                      - HTTPRoute
                      - VirtualService
                      type: string
                  required:
                  - name
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                - name
                x-kubernetes-list-type: map
              routes:
                description: route specific staging and actions
                items:
                  properties:
                    actions:
                      description: rule specific actions
                      items:
                        properties:
                          generic_key:
                            properties:
                              descriptor_key:
                                type: string
                              descriptor_value:
                                type: string
                            required:
                            - descriptor_key
                            - descriptor_value
                            type: object
                        required:
                        - generic_key
                        type: object
                      type: array
                    name:
                      description: name of the route present in the virutalservice
                      type: string
                    stage:
                      description: 'Definfing phase at which rate limits will be applied.
                        Valid values are: PREAUTH, POSTAUTH, BOTH'
                      enum:
                      - PREAUTH
                      - POSTAUTH
                      - BOTH
                      type: string
                  required:
                  - name
                  - stage
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
