
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: ratelimitpolicies.apim.kuadrant.io
spec:
  group: apim.kuadrant.io
  names:
    kind: RateLimitPolicy
    listKind: RateLimitPolicyList
    plural: ratelimitpolicies
    singular: ratelimitpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RateLimitPolicy is the Schema for the ratelimitpolicies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RateLimitPolicySpec defines the desired state of RateLimitPolicy
            properties:
              limits:
                items:
                  description: RateLimitSpec defines the desired state of RateLimit
                  properties:
                    conditions:
                      items:
                        type: string
                      type: array
                    max_value:
                      type: integer
                    namespace:
                      type: string
                    seconds:
                      type: integer
                    variables:
                      items:
                        type: string
                      type: array
                  required:
                  - conditions
                  - max_value
                  - namespace
                  - seconds
                  - variables
                  type: object
                type: array
              rateLimits:
                description: RateLimits are used for all of the matching rules
                items:
                  properties:
                    actions:
                      items:
                        description: Action_Specifier defines one envoy rate limit
                          action
                        properties:
                          generic_key:
                            properties:
                              descriptor_key:
                                type: string
                              descriptor_value:
                                type: string
                            required:
                            - descriptor_value
                            type: object
                          metadata:
                            properties:
                              default_value:
                                type: string
                              descriptor_key:
                                type: string
                              metadata_key:
                                properties:
                                  key:
                                    type: string
                                  path:
                                    items:
                                      properties:
                                        key:
                                          type: string
                                      required:
                                      - key
                                      type: object
                                    type: array
                                required:
                                - key
                                - path
                                type: object
                              source:
                                description: MetadataSource https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-enum-config-route-v3-ratelimit-action-metadata-source
                                enum:
                                - DYNAMIC
                                - ROUTE_ENTRY
                                type: string
                            required:
                            - descriptor_key
                            - metadata_key
                            type: object
                          remote_address:
                            description: RemoteAddressSpec no need to specify descriptor
                              entry is populated using the trusted address from [x-forwarded-for](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for)
                            type: object
                          request_headers:
                            description: RequestHeadersSpec Rate limit on request
                              headers.
                            properties:
                              descriptor_key:
                                type: string
                              header_name:
                                type: string
                              skip_if_absent:
                                type: boolean
                            required:
                            - descriptor_key
                            - header_name
                            type: object
                        type: object
                      type: array
                    stage:
                      description: 'Definfing phase at which rate limits will be applied.
                        Valid values are: PREAUTH, POSTAUTH, BOTH'
                      enum:
                      - PREAUTH
                      - POSTAUTH
                      - BOTH
                      type: string
                  required:
                  - stage
                  type: object
                type: array
              routes:
                description: route specific staging and actions
                items:
                  properties:
                    name:
                      description: name of the route present in the virutalservice
                      type: string
                    rateLimits:
                      items:
                        properties:
                          actions:
                            items:
                              description: Action_Specifier defines one envoy rate
                                limit action
                              properties:
                                generic_key:
                                  properties:
                                    descriptor_key:
                                      type: string
                                    descriptor_value:
                                      type: string
                                  required:
                                  - descriptor_value
                                  type: object
                                metadata:
                                  properties:
                                    default_value:
                                      type: string
                                    descriptor_key:
                                      type: string
                                    metadata_key:
                                      properties:
                                        key:
                                          type: string
                                        path:
                                          items:
                                            properties:
                                              key:
                                                type: string
                                            required:
                                            - key
                                            type: object
                                          type: array
                                      required:
                                      - key
                                      - path
                                      type: object
                                    source:
                                      description: MetadataSource https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-enum-config-route-v3-ratelimit-action-metadata-source
                                      enum:
                                      - DYNAMIC
                                      - ROUTE_ENTRY
                                      type: string
                                  required:
                                  - descriptor_key
                                  - metadata_key
                                  type: object
                                remote_address:
                                  description: RemoteAddressSpec no need to specify
                                    descriptor entry is populated using the trusted
                                    address from [x-forwarded-for](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for)
                                  type: object
                                request_headers:
                                  description: RequestHeadersSpec Rate limit on request
                                    headers.
                                  properties:
                                    descriptor_key:
                                      type: string
                                    header_name:
                                      type: string
                                    skip_if_absent:
                                      type: boolean
                                  required:
                                  - descriptor_key
                                  - header_name
                                  type: object
                              type: object
                            type: array
                          stage:
                            description: 'Definfing phase at which rate limits will
                              be applied. Valid values are: PREAUTH, POSTAUTH, BOTH'
                            enum:
                            - PREAUTH
                            - POSTAUTH
                            - BOTH
                            type: string
                        required:
                        - stage
                        type: object
                      type: array
                  required:
                  - name
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
            type: object
          status:
            description: RateLimitPolicyStatus defines the observed state of RateLimitPolicy
            properties:
              virtualservices:
                description: VirtualServices represents the current VirtualService
                  objects with reference to this ratelimitpolicy object
                items:
                  properties:
                    gateways:
                      items:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        - namespace
                        type: object
                      type: array
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
