
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: apis.networking.kuadrant.io
spec:
  group: networking.kuadrant.io
  names:
    kind: API
    listKind: APIList
    plural: apis
    singular: api
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: API is the Schema for the apis API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: APISpec defines the desired state of API
            properties:
              destination:
                properties:
                  schema:
                    type: string
                  serviceReference:
                    description: ServiceReference holds a reference to Service.legacy.k8s.io
                    properties:
                      name:
                        description: name is the name of the service. Required
                        type: string
                      namespace:
                        description: namespace is the namespace of the service. Required
                        type: string
                      path:
                        description: path is an optional URL path at which the webhook
                          will be contacted.
                        type: string
                      port:
                        description: port is an optional service port at which the
                          webhook will be contacted. `port` should be a valid port
                          number (1-65535, inclusive). Defaults to 443 for backward
                          compatibility.
                        format: int32
                        type: integer
                    required:
                    - name
                    - namespace
                    type: object
                required:
                - serviceReference
                type: object
              mappings:
                properties:
                  HTTPPathMatch:
                    description: Select a HTTP route by matching the HTTP request
                      path.
                    properties:
                      type:
                        default: Prefix
                        description: "Type specifies how to match against the path
                          Value. \n Support: Core (Exact, Prefix) \n Support: Custom
                          (RegularExpression, ImplementationSpecific) \n Since RegularExpression
                          PathType has custom conformance, implementations can support
                          POSIX, PCRE or any other dialects of regular expressions.
                          Please read the implementation's documentation to determine
                          the supported dialect."
                        enum:
                        - Exact
                        - Prefix
                        - RegularExpression
                        - ImplementationSpecific
                        type: string
                      value:
                        default: /
                        description: Value of the HTTP path to match against.
                        type: string
                    type: object
                  OAS:
                    description: Inline OAS
                    type: string
                type: object
            required:
            - destination
            - mappings
            type: object
          status:
            description: APIStatus defines the observed state of API
            properties:
              observedGeneration:
                format: int64
                type: integer
              ready:
                type: boolean
            required:
            - observedGeneration
            - ready
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
